# Generated by Django 5.2.10 on 2026-01-22 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="genre",
            field=models.CharField(default="Fiction", max_length=100),
        ),
    ]
