# Generated by Django 5.2.10 on 2026-01-29 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0002_author_genre"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="created_by",
            field=models.CharField(default="", max_length=100),
        ),
    ]
